//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSpa.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieDvd
    {
        public int MovieDvdId { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public int MovieGenreId { get; set; }
    
        public virtual MovieGenre MovieGenre { get; set; }
    }
}
